extends Node3D
## Procedural city built from a CityDef (scripts/world/cities/<id>.gd): water (rivers, lakes, the
## sea, islands), forests and zones, highways and railways with their bridges, the registry of every
## building footprint so falling debris can hit any roof. City blocks are generated by CityGen,
## unique landmarks by the city file (with the Landmarks toolkit), moving life by Life.

const Fx = preload("res://scripts/core/fx.gd")
const Meshes = preload("res://scripts/core/meshes.gd")
const Shaders = preload("res://scripts/world/shaders.gd")
const Batch = preload("res://scripts/world/batch.gd")
const CityGen = preload("res://scripts/world/city_gen.gd")
const Landmarks = preload("res://scripts/world/landmarks.gd")
const Life = preload("res://scripts/world/life.gd")
const Cities = preload("res://scripts/world/cities.gd")

const HALF := 1000.0
const ZRES := 10.0
const ZN := 200
const FCELL := 20.0
const FN := 100

# --- Water distance field: a coarse grid everywhere, a fine one along the shores ------------------
const WHALF := 1100.0
const WC_RES := 20.0
const WC_N := 111
const WF_RES := 5.0
const WF_N := 441
## "Far from any water" (the field is not computed beyond this).
const FAR := 400.0
const COARSE_REACH := 170.0
const FINE_REACH := 24.0
# --- Road / rail clearance field -----------------------------------------------------------------
const RD_RES := 5.0
const RD_N := 401
const RD_REACH := 30.0

var city_id := "kyiv"
var city
var zones := PackedByteArray()
var urb := PackedByteArray()
var targets: Array = []
## Polylines drawn on the radar (rivers, the coast).
var radar_lines: Array = []
var night := 1.0
var fog_scale := 1.0
var env: Environment
var rng := RandomNumberGenerator.new()

var _wc := PackedFloat32Array()
var _wf := PackedFloat32Array()
var _rd := PackedFloat32Array()
## Bridges actually built: {"a", "b", "deck", "style", "fp", "name"}.
var built_bridges: Array = []
## Railway tracks for the trains: {"pts": PackedVector3Array, "len": PackedFloat32Array, "trains", "cars"}.
var tracks: Array = []
## Boat lanes in the water: PackedVector2Array each.
var lanes: Array = []

# --- Footprints: everything debris can land on ----------------------------------------
var fp_center := PackedVector3Array()   # x, roof height, z
var fp_half := PackedVector2Array()
var fp_rot := PackedFloat32Array()
var fp_kind := PackedByteArray()
var fp_damaged := PackedByteArray()
## x = box height, y = pitched-roof height (0 = none) — what a collapsed building is rebuilt from.
var fp_box := PackedVector2Array()
## How much of the building has come down, 0..CRUSH_MAX.
var fp_crush := PackedFloat32Array()
var fp_hidden := PackedByteArray()
var fp_ref: Array = []                 # Vector2i into b_build, or Vector2i(-1, -1)
var fp_roof: Array = []                # Vector2i into b_roof, or Vector2i(-1, -1)
var fp_name := {}
var fp_cells := {}
var hmax := PackedFloat32Array()
## Footprints of the road bridges (the fire crews drive over them).
var road_bridge_fp: Array = []

# --- Instanced geometry -------------------------------------------------------------------------
var b_build: Batch
var b_roof: Batch
var b_lights: Batch
var b_traffic: Batch
var b_trees: Batch
var b_pines: Batch
var b_props: Batch
var b_cyl: Batch
var b_cars: Batch
var b_people: Batch
## Small things that make a street look lived in: rooftop clutter, playgrounds, pylons, parasols.
var b_detail: Batch
var b_parked: Batch
var b_neon: Batch
var neon_mat: ShaderMaterial
## How many more smoking chimneys the city generator may light (particles are not free).
var smoke_budget := 24
## Pieces glued to a building (loggias, rooftop clutter, turrets): [batch, ref, transform, roof?]
## per footprint, so they come down with the floors and come back with the repairs.
var fp_attach := {}

const BILLBOARD := [Color(1.0, 0.35, 0.5), Color(0.35, 0.8, 1.0), Color(1.0, 0.85, 0.35), Color(0.6, 1.0, 0.5), Color(0.95, 0.95, 1.0)]
const CAR_PAINT := [Color(0.9, 0.9, 0.9), Color(0.08, 0.08, 0.09), Color(0.6, 0.62, 0.65), Color(0.6, 0.08, 0.06), Color(0.1, 0.22, 0.5), Color(0.35, 0.36, 0.38), Color(0.85, 0.75, 0.3), Color(0.15, 0.35, 0.2)]
const CLOTHES := [Color(0.15, 0.15, 0.2), Color(0.5, 0.1, 0.1), Color(0.2, 0.3, 0.55), Color(0.75, 0.7, 0.6), Color(0.3, 0.45, 0.3), Color(0.9, 0.9, 0.9), Color(0.55, 0.35, 0.2), Color(0.95, 0.8, 0.2)]

var build_mat: ShaderMaterial
var lights_mat: ShaderMaterial
var traffic_mat: ShaderMaterial
var blackouts: Array = []

var _noise := FastNoiseLite.new()
var _noise2 := FastNoiseLite.new()
var _reserved: Array = []
var _res_cells := {}
## Islands and zone-only areas of the city, checked by classify().
var _zone_areas: Array = []
var _sky_mat: ShaderMaterial
var _ground_mat: ShaderMaterial
var _water_mat: ShaderMaterial
var _sun: DirectionalLight3D
var _labels: Node3D
var _hidden: Array = []
var _hidden_fp: Array = []
var gen_ms := 0


func _ready() -> void:
	build()
	GS.state_changed.connect(_on_settings)


func _on_settings() -> void:
	apply_quality(int(GS.settings.quality))


func build() -> void:
	var t0 := Time.get_ticks_msec()
	_prof_t = Time.get_ticks_usec()
	city = Cities.get_def(city_id)
	city_id = city.id
	_zone_areas = city.islands + city.parks
	rng.seed = city.seed
	_noise.seed = city.noise_seed
	_noise.frequency = 0.003
	_noise2.seed = city.noise2_seed
	_noise2.frequency = 0.011
	hmax.resize(FN * FN)
	_setup_env()
	_make_batches()
	_step("setup")
	_gen_water_field()
	_step("water field")
	_gen_route_field()
	_gen_zones()
	_step("zones")
	_gen_ground()
	_gen_water_mesh()
	city.build_outer(self)
	_step("ground+water mesh")
	Landmarks.begin(self)
	city.build_landmarks(self)
	_step("landmarks")
	_gen_routes()
	_step("roads+rails")
	CityGen.build(self)
	_step("blocks")
	_gen_forests()
	_step("forests")
	_gen_power_lines()
	_gen_beaches()
	_step("details")
	for b in [b_build, b_roof, b_lights, b_traffic, b_trees, b_pines, b_props, b_cyl, b_cars, b_people, b_detail, b_parked, b_neon]:
		(b as Batch).build(self)
	var life := Life.new()
	life.map = self
	add_child(life)
	_gen_labels()
	_step("batches+life")
	_update_blackouts()
	apply_quality(int(GS.settings.quality))
	set_night(1.0)
	gen_ms = Time.get_ticks_msec() - t0
	print("UAD: %s generated in %d ms: %d buildings, %d roofs, %d lights, %d cars, %d people, %d trees, %d bridges, %d details, %d parked" % [
		city.id, gen_ms, fp_box.size(), b_roof.count(), b_lights.count(), b_cars.count(), b_people.count(), b_trees.count() + b_pines.count(), built_bridges.size(),
		b_detail.count() + b_build.count() - fp_box.size(), b_parked.count()])


var _prof_t := 0
var _prof := OS.get_cmdline_user_args().has("--genprof")


## Generation profile (run with -- --genprof).
func _step(what: String) -> void:
	if _prof:
		var now := Time.get_ticks_usec()
		print("UAD GEN %-18s %6.1f ms" % [what, (now - _prof_t) / 1000.0])
		_prof_t = now


func _make_batches() -> void:
	build_mat = Shaders.material(Shaders.BUILDING)
	lights_mat = Shaders.material(Shaders.LIGHTS)
	traffic_mat = Shaders.material(Shaders.TRAFFIC)
	b_build = Batch.new(Fx.cube(Vector3.ONE), build_mat, true, true)
	b_build.shadows = true
	var prism := PrismMesh.new()
	prism.size = Vector3.ONE
	b_roof = Batch.new(prism, build_mat, true, true)
	b_roof.shadows = true
	b_lights = Batch.new(Fx.quad(), lights_mat, true, true)
	b_lights.aabb_margin = 80.0
	b_lights.aabb_height = 450.0
	b_traffic = Batch.new(Fx.quad(), traffic_mat, true, true)
	b_traffic.aabb_margin = 320.0
	b_trees = Batch.new(Meshes.deciduous_mesh(), Fx.vcolor(), true, false)
	b_pines = Batch.new(Meshes.conifer_mesh(), Fx.vcolor(), true, false)
	b_props = Batch.new(Fx.cube(Vector3.ONE), Fx.vcolor(), true, false)
	var cyl := CylinderMesh.new()
	cyl.top_radius = 0.5
	cyl.bottom_radius = 0.5
	cyl.height = 1.0
	cyl.radial_segments = 12
	cyl.rings = 1
	b_cyl = Batch.new(cyl, Fx.vcolor(), true, false)
	b_cyl.shadows = true
	var car_mat := Shaders.material(Shaders.CAR_BODY)
	b_cars = Batch.new(Meshes.car_mesh(), car_mat, true, true)
	b_cars.aabb_margin = 320.0
	b_cars.aabb_height = 40.0
	b_people = Batch.new(Meshes.person_mesh(), Shaders.material(Shaders.PEOPLE), true, true)
	b_people.aabb_margin = 320.0
	b_people.aabb_height = 30.0
	b_detail = Batch.new(Fx.cube(Vector3.ONE), Fx.vcolor(), true, false)
	b_parked = Batch.new(Meshes.car_mesh(), Fx.solid_vcolor_metal(), true, false)
	neon_mat = Shaders.material(Shaders.NEON)
	b_neon = Batch.new(Fx.cube(Vector3.ONE), neon_mat, true, false)


# --- Water ------------------------------------------------------------------------------------------
## Every river is a chain of capsules; lakes and islands are ellipses; the sea is the city's own
## function. The exact distance is computed once into two grids, lookups are bilinear.
func _gen_water_field() -> void:
	var segs := []
	for r in city.rivers:
		var pts: PackedVector2Array = r.pts
		var ws: PackedFloat32Array = r.w
		for i in pts.size() - 1:
			segs.append([pts[i], pts[i + 1], ws[i], ws[i + 1]])
		if float(ws[0]) >= 8.0:
			radar_lines.append(pts)
	for c in city.radar_coast():
		radar_lines.append(c)
	_wc = _water_grid(WC_RES, WC_N, COARSE_REACH, segs, true)
	_wf = _water_grid(WF_RES, WF_N, FINE_REACH, segs, false)


func _water_grid(res: float, n: int, reach: float, segs: Array, coarse: bool) -> PackedFloat32Array:
	var g := PackedFloat32Array()
	g.resize(n * n)
	g.fill(FAR)
	for s in segs:
		var a: Vector2 = s[0]
		var b: Vector2 = s[1]
		var wa: float = s[2]
		var wb: float = s[3]
		var r := maxf(wa, wb) + reach
		var x0 := maxi(0, int(floor((minf(a.x, b.x) - r + WHALF) / res)))
		var x1 := mini(n - 1, int(ceil((maxf(a.x, b.x) + r + WHALF) / res)))
		var z0 := maxi(0, int(floor((minf(a.y, b.y) - r + WHALF) / res)))
		var z1 := mini(n - 1, int(ceil((maxf(a.y, b.y) + r + WHALF) / res)))
		var abx := b.x - a.x
		var abz := b.y - a.y
		var l2 := maxf(abx * abx + abz * abz, 0.0001)
		for iz in range(z0, z1 + 1):
			var z := -WHALF + iz * res
			var row := iz * n
			for ix in range(x0, x1 + 1):
				var x := -WHALF + ix * res
				var t := clampf(((x - a.x) * abx + (z - a.y) * abz) / l2, 0.0, 1.0)
				var dx := a.x + abx * t - x
				var dz := a.y + abz * t - z
				var d := sqrt(dx * dx + dz * dz) - (wa + (wb - wa) * t)
				if d < g[row + ix]:
					g[row + ix] = d
	for l in city.lakes:
		_ellipse_into(g, res, n, reach, l, false)
	if city.has_sea and coarse:
		for iz in n:
			var z := -WHALF + iz * res
			for ix in n:
				var d: float = city.sea_dist(-WHALF + ix * res, z)
				if d < g[iz * n + ix]:
					g[iz * n + ix] = d
	elif city.has_sea:
		# the fine grid only needs the sea along the coast: coarse cells that straddle it
		var sub := int(WC_RES / res)
		for cz in WC_N - 1:
			for cx in WC_N - 1:
				var i := cz * WC_N + cx
				var mn := minf(minf(_wc[i], _wc[i + 1]), minf(_wc[i + WC_N], _wc[i + WC_N + 1]))
				var mx := maxf(maxf(_wc[i], _wc[i + 1]), maxf(_wc[i + WC_N], _wc[i + WC_N + 1]))
				if mn > 60.0 or mx < -60.0:
					continue
				for fz in sub + 1:
					var iz := cz * sub + fz
					var z := -WHALF + iz * res
					for fx in sub + 1:
						var ix := cx * sub + fx
						var d: float = city.sea_dist(-WHALF + ix * res, z)
						if d < g[iz * n + ix]:
							g[iz * n + ix] = d
	for isl in city.islands:
		_ellipse_into(g, res, n, reach, isl, true)
	return g


## Lakes join the water (min), islands cut land out of it (max with the negated distance).
func _ellipse_into(g: PackedFloat32Array, res: float, n: int, reach: float, e: Array, island: bool) -> void:
	var cx := float(e[0])
	var cz := float(e[1])
	var rx := float(e[2])
	var rz := float(e[3])
	var rot := deg_to_rad(float(e[4]) if e.size() > 4 else 0.0)
	var ca := cos(rot)
	var sa := sin(rot)
	var rm := minf(rx, rz)
	var r := maxf(rx, rz) + reach
	var x0 := maxi(0, int(floor((cx - r + WHALF) / res)))
	var x1 := mini(n - 1, int(ceil((cx + r + WHALF) / res)))
	var z0 := maxi(0, int(floor((cz - r + WHALF) / res)))
	var z1 := mini(n - 1, int(ceil((cz + r + WHALF) / res)))
	for iz in range(z0, z1 + 1):
		var z := -WHALF + iz * res - cz
		for ix in range(x0, x1 + 1):
			var x := -WHALF + ix * res - cx
			var u := (x * ca + z * sa) / rx
			var v := (-x * sa + z * ca) / rz
			var d := (sqrt(u * u + v * v) - 1.0) * rm
			var i := iz * n + ix
			if island:
				if g[i] < FAR * 0.5 and -d > g[i]:
					g[i] = -d
			elif d < g[i]:
				g[i] = d


func _coarse_at(x: float, z: float) -> float:
	var fx := clampf((x + WHALF) / WC_RES, 0.0, WC_N - 1.001)
	var fz := clampf((z + WHALF) / WC_RES, 0.0, WC_N - 1.001)
	var ix := int(fx)
	var iz := int(fz)
	var tx := fx - ix
	var tz := fz - iz
	var i := iz * WC_N + ix
	return lerpf(lerpf(_wc[i], _wc[i + 1], tx), lerpf(_wc[i + WC_N], _wc[i + WC_N + 1], tx), tz)


## Signed distance to water (negative = in the water).
func water_dist(x: float, z: float) -> float:
	var fx := (x + WHALF) / WF_RES
	var fz := (z + WHALF) / WF_RES
	var ix := int(floor(fx))
	var iz := int(floor(fz))
	if ix < 0 or iz < 0 or ix >= WF_N - 1 or iz >= WF_N - 1:
		return FAR
	var i := iz * WF_N + ix
	var a := _wf[i]
	var b := _wf[i + 1]
	var c := _wf[i + WF_N]
	var d := _wf[i + WF_N + 1]
	if a < FINE_REACH and b < FINE_REACH and c < FINE_REACH and d < FINE_REACH:
		var tx := fx - ix
		var tz := fz - iz
		return lerpf(lerpf(a, b, tx), lerpf(c, d, tx), tz)
	return _coarse_at(x, z)


## Marching squares over the fine grid along the shores, whole quads over open water.
func _gen_water_mesh() -> void:
	_water_mat = Shaders.material(Shaders.WATER)
	var verts := PackedVector3Array()
	var y := 0.35
	var sub := int(WC_RES / WF_RES)
	for cz in WC_N - 1:
		var run_start := -1
		for cx in WC_N:
			var full := false
			var edge := false
			if cx < WC_N - 1:
				var i := cz * WC_N + cx
				var v0 := _wc[i]
				var v1 := _wc[i + 1]
				var v2 := _wc[i + WC_N + 1]
				var v3 := _wc[i + WC_N]
				var mx := maxf(maxf(v0, v1), maxf(v2, v3))
				var mn := minf(minf(v0, v1), minf(v2, v3))
				full = mx < -15.0
				edge = not full and mn < 15.0
			if full and run_start < 0:
				run_start = cx
			elif not full and run_start >= 0:
				_quad(verts, -WHALF + run_start * WC_RES, -WHALF + cx * WC_RES, -WHALF + cz * WC_RES, -WHALF + (cz + 1) * WC_RES, y)
				run_start = -1
			if edge:
				for fz in sub:
					for fx in sub:
						_cell(verts, cx * sub + fx, cz * sub + fz, y)
	if verts.is_empty():
		return
	var norms := PackedVector3Array()
	norms.resize(verts.size())
	norms.fill(Vector3.UP)
	# how far from the bank (the shader makes the shallows lighter and foams the shore line)
	var cols := PackedColorArray()
	cols.resize(verts.size())
	for i in verts.size():
		var s := clampf(-water_dist(verts[i].x, verts[i].z) / 30.0, 0.0, 1.0)
		cols[i] = Color(s, s, s, 1.0)
	var a := []
	a.resize(Mesh.ARRAY_MAX)
	a[Mesh.ARRAY_VERTEX] = verts
	a[Mesh.ARRAY_NORMAL] = norms
	a[Mesh.ARRAY_COLOR] = cols
	var am := ArrayMesh.new()
	am.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, a)
	var mi := Meshes.part(self, am, _water_mat)
	mi.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF


## Open-water quads overlap their neighbours a little: rows of different length and the finer
## shore cells meet in T-junctions, which would otherwise show as hairline cracks.
func _quad(verts: PackedVector3Array, x0: float, x1: float, z0: float, z1: float, y: float) -> void:
	x0 -= 0.3
	x1 += 0.3
	z0 -= 0.3
	z1 += 0.3
	verts.append_array([Vector3(x0, y, z0), Vector3(x1, y, z0), Vector3(x1, y, z1), Vector3(x0, y, z0), Vector3(x1, y, z1), Vector3(x0, y, z1)])


## Fine-grid corner value for the shore mesh. Points the fine grid skipped are well inland (every
## point in or near the water was computed), so only the sign matters there.
func _fine_v(ix: int, iz: int) -> float:
	var v := _wf[iz * WF_N + ix]
	if v >= FAR * 0.5:
		# deep sea is never refined: trust the coarse grid there
		return minf(FINE_REACH, _coarse_at(-WHALF + ix * WF_RES, -WHALF + iz * WF_RES)) if city.has_sea else FINE_REACH
	return v


func _cell(verts: PackedVector3Array, ix: int, iz: int, y: float) -> void:
	var v := [_fine_v(ix, iz), _fine_v(ix + 1, iz), _fine_v(ix + 1, iz + 1), _fine_v(ix, iz + 1)]
	if v[0] >= 0.0 and v[1] >= 0.0 and v[2] >= 0.0 and v[3] >= 0.0:
		return
	var x0 := -WHALF + ix * WF_RES
	var z0 := -WHALF + iz * WF_RES
	var p := [Vector2(x0, z0), Vector2(x0 + WF_RES, z0), Vector2(x0 + WF_RES, z0 + WF_RES), Vector2(x0, z0 + WF_RES)]
	var poly := []
	for k in 4:
		var k2 := (k + 1) % 4
		var a: float = v[k]
		var b: float = v[k2]
		if a < 0.0:
			poly.append(p[k])
		if (a < 0.0) != (b < 0.0):
			poly.append((p[k] as Vector2).lerp(p[k2], a / (a - b)))
	for k in range(1, poly.size() - 1):
		var q0: Vector2 = poly[0]
		var q1: Vector2 = poly[k]
		var q2: Vector2 = poly[k + 1]
		verts.append_array([Vector3(q0.x, y, q0.y), Vector3(q1.x, y, q1.y), Vector3(q2.x, y, q2.y)])


func is_sea(x: float, z: float) -> bool:
	return city.has_sea and city.sea_dist(x, z) < 0.0


# --- Zones ----------------------------------------------------------------------------------------------
func classify(x: float, z: float) -> int:
	var wd := water_dist(x, z)
	if wd < 0.0:
		return GS.Zone.WATER
	var n := _noise.get_noise_2d(x, z)
	var hook: int = city.zone_hook(self, x, z, wd, n)
	if hook >= 0:
		return hook
	for isl in _zone_areas:
		if _in_ellipse(x, z, isl, 1.0):
			var iz := int(isl[5]) if (isl as Array).size() > 5 else GS.Zone.FOREST
			if iz == GS.Zone.FOREST and wd < 9.0:
				return GS.Zone.SAND
			return iz
	if city.beach_width > 0.0 and wd < city.beach_width and city.city_norm(x, z) > 0.3:
		return GS.Zone.SAND
	for f in city.forests:
		if Vector2(x - float(f[0]), z - float(f[1])).length() < float(f[2]) + n * float(f[3]):
			return GS.Zone.FOREST
	var cn: float = city.city_norm(x, z)
	if cn < 1.0 + n * 0.22:
		if _noise2.get_noise_2d(x, z) > city.park_threshold:
			return GS.Zone.FOREST # city parks
		return GS.Zone.CITY
	if cn > 1.25 and n > 0.1:
		return GS.Zone.FOREST
	return GS.Zone.FIELD


func _in_ellipse(x: float, z: float, e: Array, k: float) -> bool:
	var rot := deg_to_rad(float(e[4]) if e.size() > 4 else 0.0)
	var dx := x - float(e[0])
	var dz := z - float(e[1])
	var u := (dx * cos(rot) + dz * sin(rot)) / (float(e[2]) * k)
	var v := (-dx * sin(rot) + dz * cos(rot)) / (float(e[3]) * k)
	return u * u + v * v < 1.0


func noise_at(x: float, z: float) -> float:
	return _noise.get_noise_2d(x, z)


func _urban_level(x: float, z: float, zone: int) -> int:
	if zone == GS.Zone.CITY:
		return 2
	if zone == GS.Zone.FIELD and city.city_norm(x, z) < 1.34 + _noise.get_noise_2d(x, z) * 0.2:
		return 1
	return 0


func zone_at(x: float, z: float) -> int:
	var ix := int((x + HALF) / ZRES)
	var iz := int((z + HALF) / ZRES)
	if ix < 0 or iz < 0 or ix >= ZN or iz >= ZN:
		return GS.Zone.WATER if is_sea(x, z) else GS.Zone.FIELD
	return zones[iz * ZN + ix]


func urban_at(x: float, z: float) -> int:
	var ix := int((x + HALF) / ZRES)
	var iz := int((z + HALF) / ZRES)
	if ix < 0 or iz < 0 or ix >= ZN or iz >= ZN:
		return 0
	return urb[iz * ZN + ix]


## Base location type for a map point, or -1 when the base can't be placed there.
func location_at(x: float, z: float) -> int:
	if absf(x) > HALF - 60.0 or absf(z) > HALF - 60.0:
		return -1
	var zn := classify(x, z)
	if zn == GS.Zone.WATER or water_dist(x, z) < 12.0:
		return -1
	if is_reserved(x, z, 30.0) or road_dist(x, z) < 14.0:
		return -1
	if water_dist(x, z) < 90.0:
		return GS.Loc.RIVER
	if zn == GS.Zone.FOREST:
		var city_hits := 0
		for i in 16:
			var a := TAU * i / 16.0
			if zone_at(x + cos(a) * 130.0, z + sin(a) * 130.0) == GS.Zone.CITY:
				city_hits += 1
		return GS.Loc.CITY if city_hits >= 5 else GS.Loc.FOREST
	if zn == GS.Zone.CITY:
		return GS.Loc.CITY
	return GS.Loc.FIELD


func reserve(x: float, z: float, r: float) -> void:
	var rv := Vector3(x, z, r)
	_reserved.append(rv)
	# spatial hash: every 100 m cell the circle (plus the largest query radius) touches
	var reach := r + 45.0
	for cz in range(int(floor((z - reach) / 100.0)), int(floor((z + reach) / 100.0)) + 1):
		for cx in range(int(floor((x - reach) / 100.0)), int(floor((x + reach) / 100.0)) + 1):
			var k := cz * 1000 + cx
			if not _res_cells.has(k):
				_res_cells[k] = []
			(_res_cells[k] as Array).append(rv)


func is_reserved(x: float, z: float, r: float) -> bool:
	if r > 45.0:
		for rv in _reserved:
			if Vector2(x - rv.x, z - rv.y).length() < rv.z + r:
				return true
		return false
	var k := int(floor(z / 100.0)) * 1000 + int(floor(x / 100.0))
	if not _res_cells.has(k):
		return false
	for rv in _res_cells[k]:
		if Vector2(x - rv.x, z - rv.y).length() < rv.z + r:
			return true
	return false


# --- Highways & railways ---------------------------------------------------------------------------------
func _gen_route_field() -> void:
	_rd.resize(RD_N * RD_N)
	_rd.fill(RD_REACH)
	var list := []
	for r in city.roads:
		list.append([r.pts, float(r.w) + 1.0])
	for r in city.rails:
		list.append([r.pts, 4.0])
	for item in list:
		var pts: PackedVector2Array = item[0]
		var w: float = item[1]
		for i in pts.size() - 1:
			var a: Vector2 = pts[i]
			var b: Vector2 = pts[i + 1]
			var r := w + RD_REACH
			var x0 := maxi(0, int(floor((minf(a.x, b.x) - r + HALF) / RD_RES)))
			var x1 := mini(RD_N - 1, int(ceil((maxf(a.x, b.x) + r + HALF) / RD_RES)))
			var z0 := maxi(0, int(floor((minf(a.y, b.y) - r + HALF) / RD_RES)))
			var z1 := mini(RD_N - 1, int(ceil((maxf(a.y, b.y) + r + HALF) / RD_RES)))
			var abx := b.x - a.x
			var abz := b.y - a.y
			var l2 := maxf(abx * abx + abz * abz, 0.0001)
			for iz in range(z0, z1 + 1):
				var z := -HALF + iz * RD_RES
				for ix in range(x0, x1 + 1):
					var x := -HALF + ix * RD_RES
					var t := clampf(((x - a.x) * abx + (z - a.y) * abz) / l2, 0.0, 1.0)
					var dx := a.x + abx * t - x
					var dz := a.y + abz * t - z
					var d := sqrt(dx * dx + dz * dz) - w
					if d < _rd[iz * RD_N + ix]:
						_rd[iz * RD_N + ix] = d


## Distance to the edge of the nearest highway or railway (negative = on it).
func road_dist(x: float, z: float) -> float:
	var fx := (x + HALF) / RD_RES
	var fz := (z + HALF) / RD_RES
	var ix := int(floor(fx))
	var iz := int(floor(fz))
	if ix < 0 or iz < 0 or ix >= RD_N - 1 or iz >= RD_N - 1:
		return RD_REACH
	var i := iz * RD_N + ix
	var tx := fx - ix
	var tz := fz - iz
	return lerpf(lerpf(_rd[i], _rd[i + 1], tx), lerpf(_rd[i + RD_N], _rd[i + RD_N + 1], tx), tz)


## Splits a polyline into runs on land and over water: [[from_s, to_s, wet], ...] (s = metres).
func _wet_runs(pts: PackedVector2Array) -> Array:
	var out := []
	var s := 0.0
	var cur_wet := water_dist(pts[0].x, pts[0].y) < 0.0
	var start := 0.0
	for i in pts.size() - 1:
		var a: Vector2 = pts[i]
		var b: Vector2 = pts[i + 1]
		var l := a.distance_to(b)
		var k := maxi(1, int(ceil(l / 4.0)))
		for j in range(1, k + 1):
			var p := a.lerp(b, float(j) / k)
			var wet := water_dist(p.x, p.y) < 0.0
			var sj := s + l * float(j) / k
			if wet != cur_wet:
				out.append([start, sj, cur_wet])
				start = sj
				cur_wet = wet
		s += l
	out.append([start, s, cur_wet])
	return out


## Water crossings along a polyline as [from_s, to_s] including 34 m of approach on each bank.
## Crossings with less than 160 m of land between them (a narrow island) become one bridge.
func _crossings(pts: PackedVector2Array) -> Array:
	var out := []
	for run in _wet_runs(pts):
		if not bool(run[2]) or float(run[1]) - float(run[0]) < 6.0:
			continue
		var s0 := maxf(float(run[0]) - 34.0, 0.0)
		var s1 := float(run[1]) + 34.0
		if not out.is_empty() and s0 - float(out[out.size() - 1][1]) < 92.0:
			out[out.size() - 1][1] = s1
		else:
			out.append([s0, s1])
	return out


func _point_at(pts: PackedVector2Array, s: float) -> Vector2:
	var acc := 0.0
	for i in pts.size() - 1:
		var l := pts[i].distance_to(pts[i + 1])
		if acc + l >= s:
			return pts[i].lerp(pts[i + 1], (s - acc) / maxf(l, 0.001))
		acc += l
	return pts[pts.size() - 1]


func _gen_routes() -> void:
	var st := {"v": PackedVector3Array(), "c": PackedColorArray()}
	for r in city.roads:
		_build_road(r, st)
	for r in city.rails:
		_build_rail(r, st)
	for b in city.bridges:
		var bd: Dictionary = Landmarks.bridge(self, b.a, b.b, String(b.style), String(b.name), bool(b.get("target", false)))
		built_bridges.append(bd)
		if String(b.style) != "rail" and String(b.style) != "pedestrian":
			road_bridge_fp.append(int(bd.fp))
	var verts: PackedVector3Array = st.v
	if verts.is_empty():
		return
	var norms := PackedVector3Array()
	norms.resize(verts.size())
	norms.fill(Vector3.UP)
	var a := []
	a.resize(Mesh.ARRAY_MAX)
	a[Mesh.ARRAY_VERTEX] = verts
	a[Mesh.ARRAY_NORMAL] = norms
	a[Mesh.ARRAY_COLOR] = st.c
	var am := ArrayMesh.new()
	am.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, a)
	var mi := Meshes.part(self, am, Shaders.material(Shaders.FLAT))
	mi.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF


## A flat strip of width 2·w along a→b at height y (clockwise from above, as the ground).
func _strip(st: Dictionary, a: Vector2, b: Vector2, w: float, y: float, col: Color) -> void:
	var d := (b - a).normalized()
	var s := Vector2(-d.y, d.x) * w
	var p0 := a - s
	var p1 := a + s
	var p2 := b + s
	var p3 := b - s
	# keep the winding clockwise seen from above whatever the direction
	var cross := (p1 - p0).x * (p2 - p0).y - (p1 - p0).y * (p2 - p0).x
	var q := [p0, p1, p2, p3] if cross > 0.0 else [p0, p3, p2, p1]
	var v: PackedVector3Array = st.v
	var c: PackedColorArray = st.c
	for i in [0, 1, 2, 0, 2, 3]:
		var p: Vector2 = q[i]
		v.append(Vector3(p.x, y, p.y))
		c.append(col)
	st.v = v
	st.c = c


func _build_road(r: Dictionary, st: Dictionary) -> void:
	var pts: PackedVector2Array = r.pts
	var w: float = r.w
	var specs: Array = r.get("bridges", [])
	var asphalt := Color(0.07, 0.07, 0.075)
	var paint := Color(0.75, 0.75, 0.7)
	var total := 0.0
	for i in pts.size() - 1:
		total += pts[i].distance_to(pts[i + 1])
	# one bridge per water crossing, the land runs between them get the asphalt
	var land := []
	var at := 0.0
	var cr := _crossings(pts)
	for k in cr.size():
		var spec: Dictionary = specs[k] if k < specs.size() else {}
		var bd: Dictionary = Landmarks.bridge(self, _point_at(pts, cr[k][0]), _point_at(pts, cr[k][1]), String(spec.get("style", "girder")), String(spec.get("name", "мост")), bool(spec.get("target", false)))
		built_bridges.append(bd)
		road_bridge_fp.append(int(bd.fp))
		land.append([at, float(cr[k][0]) + 34.0])
		at = float(cr[k][1]) - 34.0
	land.append([at, total])
	for run in land:
		var s0: float = run[0]
		var s1: float = run[1]
		if s1 - s0 < 5.0:
			continue
		# land: asphalt, markings, lamps, traffic, pedestrians
		var s := s0
		var seg_a := _point_at(pts, s)
		var run_a := seg_a
		var run_dir := Vector2.ZERO
		var lamp_s := s0 + 12.0
		while s < s1 - 0.5:
			var s2 := minf(s + 10.0, s1)
			var seg_b := _point_at(pts, s2)
			if seg_a.distance_to(seg_b) > 0.3:
				_strip(st, seg_a, seg_b, w, 0.12, asphalt)
				_strip(st, seg_a, seg_b, 0.18, 0.2, paint)
				var dn := (seg_b - seg_a).normalized()
				var side := Vector2(-dn.y, dn.x)
				for sg in [-1.0, 1.0]:
					_strip(st, seg_a + side * sg * (w - 0.7), seg_b + side * sg * (w - 0.7), 0.12, 0.2, paint)
				if run_dir == Vector2.ZERO:
					run_dir = dn
				elif run_dir.angle_to(dn) > 0.12 or run_a.distance_to(seg_b) > 220.0:
					add_traffic(run_a, seg_a, 1.1)
					add_people(run_a, seg_a, w + 2.5)
					run_a = seg_a
					run_dir = dn
				while lamp_s < s2:
					var lp := _point_at(pts, lamp_s)
					for sg in [-1.0, 1.0]:
						var q: Vector2 = lp + side * sg * (w + 1.2)
						add_light(Vector3(q.x, 9.0, q.y), Color(0.85, 0.9, 1.0), false, 1.0, 0.0021)
						add_solid(Vector3(q.x, 4.5, q.y), Vector3(0.28, 9.0, 0.28), 0.0, Color(0.22, 0.22, 0.24))
					lamp_s += 32.0
			seg_a = seg_b
			s = s2
		if run_a.distance_to(seg_a) > 40.0:
			add_traffic(run_a, seg_a, 1.1)
			add_people(run_a, seg_a, w + 2.5)
		# lit billboards along the highway, on alternating sides
		var bs := s0 + 90.0
		var side_k := 1.0
		while bs < s1 - 40.0:
			var bp := _point_at(pts, bs)
			var bd := (_point_at(pts, bs + 5.0) - bp).normalized()
			var nrm := Vector2(-bd.y, bd.x) * side_k
			var q: Vector2 = bp + nrm * (w + 7.0)
			if building_at(q.x, q.y) < 0 and water_dist(q.x, q.y) > 4.0 and not is_reserved(q.x, q.y, 3.0):
				add_detail(Vector3(q.x, 5.0, q.y), Vector3(0.5, 10.0, 0.5), 0.0, Color(0.3, 0.3, 0.32))
				var board := MeshInstance3D.new()
				board.mesh = Fx.cube(Vector3(9.0, 4.2, 0.3))
				board.material_override = Fx.glow(BILLBOARD[rng.randi() % BILLBOARD.size()], 1.1)
				board.position = Vector3(q.x, 11.6, q.y)
				board.rotation.y = atan2(bd.x, bd.y) + PI * 0.5
				board.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
				add_child(board)
				add_footprint(q, Vector2(4.5, 0.5), -board.rotation.y, 14.0, 2, "рекламный щит")
			side_k = -side_k
			bs += rng.randf_range(260.0, 360.0)


func _build_rail(r: Dictionary, st: Dictionary) -> void:
	var pts: PackedVector2Array = r.pts
	var spans := _crossings(pts)
	var spec: Dictionary = r.get("bridge", {})
	for sp in spans:
		var bd: Dictionary = Landmarks.bridge(self, _point_at(pts, sp[0]), _point_at(pts, sp[1]), "rail", String(spec.get("name", "железнодорожный мост")), bool(spec.get("target", false)))
		built_bridges.append(bd)
	# height profile: the rail deck on the bridges, 90 m ramps down to the ground
	var total := 0.0
	for i in pts.size() - 1:
		total += pts[i].distance_to(pts[i + 1])
	var track := PackedVector3Array()
	var lens := PackedFloat32Array()
	var s := 0.0
	var gravel := Color(0.2, 0.19, 0.18)
	var steel := Color(0.55, 0.55, 0.58)
	var prev := Vector3.ZERO
	while s <= total + 0.01:
		var p := _point_at(pts, s)
		var y := 0.0
		for sp in spans:
			var d := 0.0
			if s < float(sp[0]):
				d = float(sp[0]) - s
			elif s > float(sp[1]):
				d = s - float(sp[1])
			y = maxf(y, Landmarks.RAIL_DECK * clampf(1.0 - d / 90.0, 0.0, 1.0))
		var cur := Vector3(p.x, y, p.y)
		if not track.is_empty():
			var on_bridge := false
			for sp in spans:
				if s > float(sp[0]) + 1.0 and s - 8.0 < float(sp[1]) - 1.0:
					on_bridge = true
			var a := Vector2(prev.x, prev.z)
			var b := Vector2(cur.x, cur.z)
			if not on_bridge and a.distance_to(b) > 0.3:
				var yy := maxf(prev.y, cur.y)
				if yy > 0.4:
					# embankment under the ramp
					var mid := (a + b) * 0.5
					add_solid(Vector3(mid.x, yy * 0.5, mid.y), Vector3(5.0, yy, a.distance_to(b) + 0.4), atan2(b.x - a.x, b.y - a.y), Color(0.3, 0.28, 0.26))
				_strip(st, a, b, 2.6, 0.07 + yy, gravel)
				var dn := (b - a).normalized()
				var side := Vector2(-dn.y, dn.x)
				for sg in [-0.75, 0.75]:
					_strip(st, a + side * sg, b + side * sg, 0.1, 0.12 + yy, steel)
		track.append(cur)
		lens.append(s)
		prev = cur
		if s >= total:
			break
		s = minf(s + 8.0, total)
	tracks.append({"pts": track, "len": lens, "trains": int(r.get("trains", 1)), "cars": int(r.get("cars", 7))})


# --- Footprints ----------------------------------------------------------------------------------
func _cell_key(ix: int, iz: int) -> int:
	return iz * 1000 + ix


func _register(c: Vector2, half: Vector2, rot: float, h: float, kind: int, fname: String, ref: Vector2i, roof: Vector2i) -> int:
	var i := fp_center.size()
	fp_center.append(Vector3(c.x, h, c.y))
	fp_half.append(half)
	fp_rot.append(rot)
	fp_kind.append(kind)
	fp_damaged.append(0)
	fp_box.append(Vector2.ZERO)
	fp_crush.append(0.0)
	fp_hidden.append(0)
	fp_ref.append(ref)
	fp_roof.append(roof)
	if fname != "":
		fp_name[i] = fname
	var r := half.length()
	var x0 := int(floor((c.x - r + HALF) / FCELL))
	var x1 := int(floor((c.x + r + HALF) / FCELL))
	var z0 := int(floor((c.y - r + HALF) / FCELL))
	var z1 := int(floor((c.y + r + HALF) / FCELL))
	for iz in range(z0, z1 + 1):
		for ix in range(x0, x1 + 1):
			var k := _cell_key(ix, iz)
			if not fp_cells.has(k):
				fp_cells[k] = []
			(fp_cells[k] as Array).append(i)
			if ix >= 0 and iz >= 0 and ix < FN and iz < FN:
				hmax[iz * FN + ix] = maxf(hmax[iz * FN + ix], h)
	return i


## A visible building (unit cube scaled + rotated) with an optional pitched roof.
func add_building(c: Vector2, half: Vector2, rot: float, h: float, style: int, col: Color, kind := 0, roof_h := 0.0, roof_col := Color(0.45, 0.2, 0.15), fname := "") -> int:
	var basis := Basis(Vector3.UP, -rot) * Basis.from_scale(Vector3(half.x * 2.0, h, half.y * 2.0))
	var ref := b_build.add(Transform3D(basis, Vector3(c.x, h * 0.5, c.y)), col, Color(0.0, rng.randf(), style / 10.0, 0.0))
	var roof := Vector2i(-1, -1)
	if roof_h > 0.0:
		var rb: Basis
		if half.x > half.y:
			rb = Basis(Vector3.UP, -rot + PI * 0.5) * Basis.from_scale(Vector3(half.y * 2.0, roof_h, half.x * 2.0))
		else:
			rb = Basis(Vector3.UP, -rot) * Basis.from_scale(Vector3(half.x * 2.0, roof_h, half.y * 2.0))
		roof = b_roof.add(Transform3D(rb, Vector3(c.x, h + roof_h * 0.5, c.y)), roof_col, Color(0.0, rng.randf(), 0.7, 0.0))
	var i := _register(c, half, rot, h + roof_h * 0.6, kind, fname, ref, roof)
	fp_box[i] = Vector2(h, roof_h)
	return i


## Invisible footprint for individually modelled landmarks.
func add_footprint(c: Vector2, half: Vector2, rot: float, h: float, kind := 2, fname := "") -> int:
	return _register(c, half, rot, h, kind, fname, Vector2i(-1, -1), Vector2i(-1, -1))


## Decorative box using the building shader (no collision), e.g. rooftop machine rooms.
func add_prop_box(center: Vector3, size: Vector3, rot: float, col: Color, style := 6) -> Vector2i:
	var basis := Basis(Vector3.UP, -rot) * Basis.from_scale(size)
	return b_build.add(Transform3D(basis, center), col, Color(0.0, rng.randf(), style / 10.0, 0.0))


func add_solid(center: Vector3, size: Vector3, rot: float, col: Color) -> void:
	b_props.add(Transform3D(Basis(Vector3.UP, -rot) * Basis.from_scale(size), center), col)


func add_cyl(base: Vector3, r: float, h: float, col: Color) -> Vector2i:
	return b_cyl.add(Transform3D(Basis.from_scale(Vector3(r * 2.0, h, r * 2.0)), base + Vector3(0, h * 0.5, 0)), col)


## A small unlit prop box (AC units, slides, pylons …).
func add_detail(center: Vector3, size: Vector3, rot: float, col: Color) -> Vector2i:
	return b_detail.add(Transform3D(Basis(Vector3.UP, -rot) * Basis.from_scale(size), center), col)


## A glowing sign / shop front / neon strip.
func add_neon(center: Vector3, size: Vector3, rot: float, col: Color) -> Vector2i:
	return b_neon.add(Transform3D(Basis(Vector3.UP, -rot) * Basis.from_scale(size), center), col)


## Smoke rising from a chimney top (a limited number per city).
func add_smoke(top: Vector3, dark := true) -> void:
	if smoke_budget <= 0:
		return
	smoke_budget -= 1
	var sm := CPUParticles3D.new()
	sm.mesh = Fx.sphere(1.0, 6)
	sm.material_override = Fx.smoke_mat()
	sm.amount = 14
	sm.lifetime = 7.0
	sm.direction = Vector3.UP
	sm.spread = 10.0
	sm.initial_velocity_min = 3.0
	sm.initial_velocity_max = 5.0
	sm.gravity = Vector3(1.6, 0.5, 0.6)
	sm.scale_amount_min = 2.5
	sm.scale_amount_max = 6.0
	var g := Gradient.new()
	g.set_color(0, Color(0.45, 0.43, 0.42, 0.45) if dark else Color(0.8, 0.8, 0.82, 0.35))
	g.set_color(1, Color(0.4, 0.4, 0.42, 0.0))
	sm.color_ramp = g
	sm.position = top
	add_child(sm)


## A parked car at the kerb, its nose towards world direction `dir`.
func add_parked(p: Vector2, dir: Vector2, col: Color) -> void:
	b_parked.add(Transform3D(Basis(Vector3.UP, atan2(-dir.x, -dir.y)), Vector3(p.x, 0.0, p.y)), col)


## Glues a prop to building `i`: "wall" pieces shrink with the collapsed floors, "roof" pieces
## are gone while the building is damaged.
func attach(i: int, batch: Batch, ref: Vector2i, roof: bool) -> void:
	if i < 0 or ref.x < 0:
		return
	if not fp_attach.has(i):
		fp_attach[i] = []
	(fp_attach[i] as Array).append([batch, ref, batch.get_xform(ref), roof])


func add_light(pos: Vector3, col: Color, blink := false, base := 1.0, k := 0.0025) -> void:
	b_lights.add(Transform3D(Basis(), pos), col, Color(rng.randf(), 1.0 if blink else 0.0, base, k))


## Two opposite streams of car lights between a and b.
func add_traffic(a: Vector2, b: Vector2, density := 1.0, y := 0.0) -> void:
	var d := b - a
	var length := d.length()
	if length < 40.0:
		return
	var dir := d / length
	var side := Vector2(-dir.y, dir.x)
	var n := maxi(1, int(length / 38.0 * density))
	for lane in 2:
		var from := a if lane == 0 else b
		var to_dir := dir if lane == 0 else -dir
		var off := side * (2.6 if lane == 0 else -2.6)
		var basis := Basis.looking_at(Vector3(to_dir.x, 0, to_dir.y), Vector3.UP)
		var col := Color(1.0, 0.93, 0.78) if lane == 0 else Color(1.0, 0.12, 0.07)
		for i in n:
			var o := from + off
			var xf := Transform3D(basis, Vector3(o.x, y, o.y))
			var cd := Color(rng.randf_range(9.0, 16.0), length, rng.randf(), 0.0)
			b_traffic.add(xf, col, cd)
			b_cars.add(xf, CAR_PAINT[rng.randi() % CAR_PAINT.size()], cd)


## Pedestrians walking both ways along the sidewalks of a street segment.
func add_people(a: Vector2, b: Vector2, sidewalk: float, y := 0.0) -> void:
	var d := b - a
	var length := d.length()
	if length < 30.0:
		return
	var dir := d / length
	var side := Vector2(-dir.y, dir.x)
	for s in [-1.0, 1.0]:
		var n := int(length / 22.0)
		for i in n:
			var fwd := rng.randf() < 0.5
			var start: Vector2 = a if fwd else b
			var from: Vector2 = start + side * float(s) * (sidewalk + rng.randf_range(-0.8, 0.8))
			var to_dir: Vector2 = dir if fwd else -dir
			var basis := Basis.looking_at(Vector3(to_dir.x, 0, to_dir.y), Vector3.UP)
			var cd := Color(rng.randf_range(1.1, 1.8), length, rng.randf(), rng.randf())
			b_people.add(Transform3D(basis, Vector3(from.x, y, from.y)), CLOTHES[rng.randi() % CLOTHES.size()], cd)


## Bridge decks are walkable surfaces for the pedestrian view.
func is_deck(i: int) -> bool:
	return String(fp_name.get(i, "")).to_lower().contains("мост")


func add_tree(p: Vector2, s: float, col: Color, conifer := false) -> void:
	var xf := Transform3D(Basis(Vector3.UP, rng.randf() * TAU) * Basis.from_scale(Vector3.ONE * s), Vector3(p.x, 0, p.y))
	if conifer:
		b_pines.add(xf, col)
	else:
		b_trees.add(xf, col)


func building_at(x: float, z: float) -> int:
	var k := _cell_key(int(floor((x + HALF) / FCELL)), int(floor((z + HALF) / FCELL)))
	if not fp_cells.has(k):
		return -1
	var best := -1
	var best_h := -1.0
	for i in fp_cells[k]:
		if fp_hidden[i] == 1:
			continue
		var c := fp_center[i]
		var dx := x - c.x
		var dz := z - c.z
		var ca := cos(fp_rot[i])
		var sa := sin(fp_rot[i])
		var lx := dx * ca + dz * sa
		var lz := -dx * sa + dz * ca
		var hs := fp_half[i]
		if absf(lx) <= hs.x and absf(lz) <= hs.y and c.y > best_h:
			best = i
			best_h = c.y
	return best


func ground_height(x: float, z: float) -> float:
	var bi := building_at(x, z)
	return fp_center[bi].y if bi >= 0 else 0.0


## Highest roof in the 3×3 cells around a point (for terrain-following flight).
func ceiling(x: float, z: float) -> float:
	var ix := int(floor((x + HALF) / FCELL))
	var iz := int(floor((z + HALF) / FCELL))
	var m := 0.0
	for dz in range(-1, 2):
		for dx in range(-1, 2):
			var cx := ix + dx
			var cz := iz + dz
			if cx >= 0 and cz >= 0 and cx < FN and cz < FN:
				m = maxf(m, hmax[cz * FN + cx])
	return m


## Road bridge decks: the only way across the water for anything that drives.
func bridge_points() -> Array:
	var out := []
	for i in road_bridge_fp:
		out.append(fp_center[int(i)])
	return out


func is_bridge(i: int) -> bool:
	return i >= 0 and String(fp_name.get(i, "")).to_lower().contains("мост")


## Name of the district a point falls in — used by the highlight reel captions.
func district_name(x: float, z: float) -> String:
	return String(city.districts[CityGen.nearest(city.districts, x, z)][0])


func building_kind(i: int) -> int:
	return fp_kind[i]


func building_name(i: int) -> String:
	return GS.t(String(fp_name.get(i, GS.KIND_NAME[fp_kind[i]])))


func damage_building(i: int) -> bool:
	if fp_damaged[i] == 1:
		return false
	fp_damaged[i] = 1
	var ref: Vector2i = fp_ref[i]
	if ref.x >= 0:
		var cd := b_build.get_custom(ref)
		b_build.set_custom(ref, Color(1.0, cd.g, cd.b, 0))
	var roof: Vector2i = fp_roof[i]
	if roof.x >= 0:
		var rc := b_roof.get_custom(roof)
		b_roof.set_custom(roof, Color(1.0, rc.g, rc.b, 0))
	return true


## A building never comes down completely: the lower floors and the walls stay standing.
const CRUSH_MAX := 0.55


## Takes `amount` (0..1 of the original height) off a building: the upper floors collapse,
## a pitched roof is gone with them. Returns how many metres came down (0 = nothing moved).
func crush_building(i: int, amount: float) -> float:
	if i < 0 or i >= fp_crush.size() or fp_box[i].x <= 0.0 or fp_ref[i].x < 0:
		return 0.0
	var before: float = fp_crush[i]
	var after: float = minf(CRUSH_MAX, before + amount)
	if after - before < 0.01:
		return 0.0
	fp_crush[i] = after
	_apply_crush(i)
	return fp_box[i].x * (after - before)


## Rebuilds part of a collapsed building (the repair crews work gradually).
## Returns true once it stands at its full height again.
func repair_building(i: int, amount := 1.0) -> bool:
	if i < 0 or i >= fp_crush.size():
		return true
	if fp_crush[i] > 0.0:
		fp_crush[i] = maxf(0.0, fp_crush[i] - amount)
		_apply_crush(i)
	if fp_crush[i] > 0.0:
		return false
	undamage_building(i)
	return true


## Scale the box down to the height that is left and drop the roof cap with it.
func _apply_crush(i: int) -> void:
	var ref: Vector2i = fp_ref[i]
	if ref.x < 0:
		return
	var c: Vector3 = fp_center[i]
	var half: Vector2 = fp_half[i]
	var box: Vector2 = fp_box[i]
	var crush: float = fp_crush[i]
	var h: float = box.x * (1.0 - crush)
	var basis := Basis(Vector3.UP, -fp_rot[i]) * Basis.from_scale(Vector3(half.x * 2.0, h, half.y * 2.0))
	b_build.set_xform(ref, Transform3D(basis, Vector3(c.x, h * 0.5, c.z)))
	var roof: Vector2i = fp_roof[i]
	if roof.x >= 0:
		if crush > 0.01:
			b_roof.hide(roof)
		else:
			b_roof.unhide(roof)
	for a in fp_attach.get(i, []):
		var bt: Batch = a[0]
		if bool(a[3]):
			if crush > 0.01:
				bt.hide(a[1])
			else:
				bt.unhide(a[1])
		else:
			# a wall piece standing on the ground keeps its foot and loses its top with the floors
			var xf: Transform3D = a[2]
			var hh := xf.basis.get_scale().y
			var foot := xf.origin.y - hh * 0.5
			var nh := maxf(0.2, minf(hh, h - foot))
			var nb := xf.basis.orthonormalized() * Basis.from_scale(Vector3(xf.basis.get_scale().x, nh, xf.basis.get_scale().z))
			bt.set_xform(a[1], Transform3D(nb, Vector3(xf.origin.x, foot + nh * 0.5, xf.origin.z)))
	fp_center[i] = Vector3(c.x, h + (0.0 if crush > 0.01 else box.y * 0.6), c.z)


func crush_of(i: int) -> float:
	return fp_crush[i] if i >= 0 and i < fp_crush.size() else 0.0


## Soot and boarded-up windows go away when the building is repaired.
func undamage_building(i: int) -> void:
	if i < 0 or i >= fp_damaged.size() or fp_damaged[i] == 0:
		return
	fp_damaged[i] = 0
	var ref: Vector2i = fp_ref[i]
	if ref.x >= 0:
		var cd := b_build.get_custom(ref)
		b_build.set_custom(ref, Color(0.0, cd.g, cd.b, 0))
	var roof: Vector2i = fp_roof[i]
	if roof.x >= 0:
		var rc := b_roof.get_custom(roof)
		b_roof.set_custom(roof, Color(0.0, rc.g, rc.b, 0))


func damaged_list() -> Array:
	var out := []
	for i in fp_damaged.size():
		if fp_damaged[i] == 1:
			out.append(i)
	return out


## Collapsed buildings for the save file: [index, percent] pairs.
func crushed_list() -> Array:
	var out := []
	for i in fp_crush.size():
		if fp_crush[i] > 0.0:
			out.append([i, int(round(fp_crush[i] * 100.0))])
	return out


func apply_crush_list(list: Array) -> void:
	for v in list:
		if v is Array and (v as Array).size() == 2:
			var i := int(v[0])
			if i >= 0 and i < fp_crush.size() and fp_box[i].x > 0.0 and fp_ref[i].x >= 0:
				fp_crush[i] = clampf(float(v[1]) * 0.01, 0.0, CRUSH_MAX)
				_apply_crush(i)


## Multiplayer guest: makes the buildings exactly what the host has — sooty roofs `damaged`
## (indices) and collapsed floors `crushed` ([index, percent]). Returns [index, height lost] for
## the buildings that came down further since the last state (the game shows them collapse).
func sync_damage(damaged: Array, crushed: Array) -> Array:
	var want_d := {}
	for v in damaged:
		want_d[int(v)] = true
	for i in fp_damaged.size():
		if fp_damaged[i] == 1 and not want_d.has(i):
			undamage_building(i)
	for i in want_d:
		if i >= 0 and i < fp_damaged.size():
			damage_building(i)
	var want_c := {}
	for v in crushed:
		if v is Array and (v as Array).size() == 2:
			want_c[int(v[0])] = clampf(float(v[1]) * 0.01, 0.0, CRUSH_MAX)
	var fell := []
	for i in fp_crush.size():
		var w := float(want_c.get(i, 0.0))
		if absf(fp_crush[i] - w) < 0.005 or fp_box[i].x <= 0.0 or fp_ref[i].x < 0:
			continue
		if w > fp_crush[i]:
			fell.append([i, fp_box[i].x * (w - fp_crush[i])])
		fp_crush[i] = w
		_apply_crush(i)
	return fell


## Multiplayer guest: the host's blackouts (x, z, radius, 1).
func set_blackouts(list: Array) -> void:
	blackouts.clear()
	for v in list:
		blackouts.append(v)
	_update_blackouts()


func apply_damage_list(list: Array) -> void:
	for v in list:
		var i := int(v)
		if i >= 0 and i < fp_damaged.size():
			damage_building(i)


func reset_damage() -> void:
	for i in fp_crush.size():
		if fp_crush[i] > 0.0:
			fp_crush[i] = 0.0
			_apply_crush(i)
	for i in fp_damaged.size():
		if fp_damaged[i] == 1:
			fp_damaged[i] = 0
			var ref: Vector2i = fp_ref[i]
			if ref.x >= 0:
				var cd := b_build.get_custom(ref)
				b_build.set_custom(ref, Color(0.0, cd.g, cd.b, 0))
			var roof: Vector2i = fp_roof[i]
			if roof.x >= 0:
				var rc := b_roof.get_custom(roof)
				b_roof.set_custom(roof, Color(0.0, rc.g, rc.b, 0))


## Removes buildings, trees and props under the player's base footprint.
func clear_area(c: Vector3, r: float) -> void:
	restore_area()
	for b in [b_build, b_roof, b_trees, b_pines, b_props, b_cyl, b_lights, b_detail, b_parked]:
		for ref in (b as Batch).refs_near(c, r + 8.0):
			(b as Batch).hide(ref)
			_hidden.append([b, ref])
	for i in fp_center.size():
		if fp_hidden[i] == 0 and Vector2(fp_center[i].x - c.x, fp_center[i].z - c.z).length() < r + 8.0:
			fp_hidden[i] = 1
			_hidden_fp.append(i)


func restore_area() -> void:
	for h in _hidden:
		(h[0] as Batch).unhide(h[1])
	for i in _hidden_fp:
		fp_hidden[i] = 0
	_hidden.clear()
	_hidden_fp.clear()


## Nearest point to `p` where a base of the given type can stand (or of any type when there is none
## close by) — older saves may have their base where the reworked map now has water or a highway.
func nearest_base_spot(p: Vector3, loc: int) -> Vector3:
	if location_at(p.x, p.z) >= 0:
		return p
	var fallback := Vector3.INF
	var r := 20.0
	while r < 700.0:
		var steps := int(TAU * r / 20.0)
		for i in steps:
			var a := TAU * i / steps
			var q := p + Vector3(cos(a) * r, 0, sin(a) * r)
			var l := location_at(q.x, q.z)
			if l == loc:
				return q
			if l >= 0 and fallback == Vector3.INF:
				fallback = q
		if fallback != Vector3.INF and r > 150.0:
			return fallback
		r += 20.0
	return fallback if fallback != Vector3.INF else p


func set_labels_visible(v: bool) -> void:
	_labels.visible = v


# --- Blackouts (power plant hit → district goes dark) -----------------------------------------
func add_blackout(p: Vector3, r: float) -> void:
	blackouts.append(Vector4(p.x, p.z, r, 1.0))
	while blackouts.size() > 4:
		blackouts.pop_front()
	_update_blackouts()


func clear_blackouts() -> void:
	blackouts.clear()
	_update_blackouts()


func _update_blackouts() -> void:
	var arr := PackedVector4Array()
	for i in 4:
		arr.append(blackouts[i] if i < blackouts.size() else Vector4(0, 0, 0, 0))
	for m in [build_mat, lights_mat, traffic_mat, _ground_mat, neon_mat]:
		(m as ShaderMaterial).set_shader_parameter("blackouts", arr)


# --- Generation ----------------------------------------------------------------------------------
func _gen_zones() -> void:
	zones.resize(ZN * ZN)
	urb.resize(ZN * ZN)
	for iz in ZN:
		for ix in ZN:
			var x := -HALF + (ix + 0.5) * ZRES
			var z := -HALF + (iz + 0.5) * ZRES
			var zn := classify(x, z)
			zones[iz * ZN + ix] = zn
			urb[iz * ZN + ix] = _urban_level(x, z, zn)


func _gen_ground() -> void:
	var img := Image.create_empty(ZN, ZN, false, Image.FORMAT_RGBA8)
	for iz in ZN:
		for ix in ZN:
			var zn := zones[iz * ZN + ix]
			var u := urb[iz * ZN + ix]
			var c: Color
			match zn:
				GS.Zone.FOREST:
					c = Color(0.06, 0.13, 0.05)
				GS.Zone.WATER:
					c = Color(0.02, 0.05, 0.09)
				GS.Zone.CITY:
					c = Color(0.16, 0.16, 0.17)
				GS.Zone.SAND:
					c = Color(0.52, 0.47, 0.34)
				_:
					c = Color(0.19, 0.21, 0.12) if u == 0 else Color(0.17, 0.2, 0.12)
			c.a = 1.0 if u == 2 else (0.5 if u == 1 else 0.0)
			img.set_pixel(ix, iz, c)
	_ground_mat = Shaders.material(Shaders.GROUND)
	_ground_mat.set_shader_parameter("zone_tex", ImageTexture.create_from_image(img))
	_ground_mat.set_shader_parameter("half_size", HALF)
	var ds := PackedVector4Array()
	for d in city.districts:
		ds.append(Vector4(d[1], d[2], deg_to_rad(d[3]), d[4]))
	while ds.size() < Shaders.MAX_DISTRICTS:
		ds.append(Vector4(99999, 99999, 0, 50))
	_ground_mat.set_shader_parameter("districts", ds)
	_ground_mat.set_shader_parameter("district_count", city.districts.size())
	var pm := PlaneMesh.new()
	pm.size = Vector2(HALF * 2.0, HALF * 2.0)
	pm.subdivide_width = 20
	pm.subdivide_depth = 20
	Meshes.part(self, pm, _ground_mat)
	_gen_outer()


## The country beyond the map out to the horizon (Shaders.OUTER): fields, woods and villages, and
## the highways, railways and rivers of the map carried on from where they leave it.
func _gen_outer() -> void:
	var exits := PackedVector4Array()
	var dirs := PackedVector4Array()
	var add_exit := func(a: Vector2, b: Vector2, kind: int, w: float) -> void:
		# b is the end of a line, a the point before it: does the line run off the map there?
		if maxf(absf(b.x), absf(b.y)) < HALF * 0.8 or exits.size() >= 20:
			return
		var d := (b - a).normalized()
		if d == Vector2.ZERO:
			return
		exits.append(Vector4(b.x, b.y, kind, w))
		dirs.append(Vector4(d.x, d.y, float(exits.size()) * 1.7, 0.0))
	for r in city.rivers:
		var pts: PackedVector2Array = r.pts
		var ws: PackedFloat32Array = r.get("w", PackedFloat32Array())
		if pts.size() >= 2:
			add_exit.call(pts[1], pts[0], 2, ws[0] if ws.size() > 0 else 40.0)
			add_exit.call(pts[pts.size() - 2], pts[pts.size() - 1], 2, ws[ws.size() - 1] if ws.size() > 0 else 40.0)
	for r in city.roads:
		var pts: PackedVector2Array = r.pts
		if pts.size() >= 2:
			add_exit.call(pts[1], pts[0], 0, float(r.w))
			add_exit.call(pts[pts.size() - 2], pts[pts.size() - 1], 0, float(r.w))
	for r in city.rails:
		var pts: PackedVector2Array = r.pts
		if pts.size() >= 2:
			add_exit.call(pts[1], pts[0], 1, 3.0)
			add_exit.call(pts[pts.size() - 2], pts[pts.size() - 1], 1, 3.0)
	var mat := Shaders.material(Shaders.OUTER)
	var count := exits.size()
	while exits.size() < 20:
		exits.append(Vector4(99999, 99999, 0, 0))
		dirs.append(Vector4(1, 0, 0, 0))
	mat.set_shader_parameter("exits", exits)
	mat.set_shader_parameter("exit_dirs", dirs)
	mat.set_shader_parameter("exit_count", count)
	mat.set_shader_parameter("map_half", HALF)
	# a ring around the map, not a plane under it: two surfaces 0.4 m apart all over the city
	# fought for the depth buffer from a kilometre or two away and the fields flickered through
	# the streets. The ring tucks one metre under the map's edge, so no seam can open.
	var R := 22000.0
	var h := HALF - 1.0
	var st := SurfaceTool.new()
	st.begin(Mesh.PRIMITIVE_TRIANGLES)
	st.set_normal(Vector3.UP)
	for q in [[-R, -R, R, -h], [-R, h, R, R], [-R, -h, -h, h], [h, -h, R, h]]:
		var a := Vector3(q[0], 0.0, q[1])
		var b := Vector3(q[2], 0.0, q[1])
		var c := Vector3(q[2], 0.0, q[3])
		var d := Vector3(q[0], 0.0, q[3])
		for v in [a, b, c, a, c, d]:
			st.add_vertex(v)
	var outer := st.commit()
	var mi := Meshes.part(self, outer, mat, Vector3(0, -0.4, 0))
	mi.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF


func _gen_forests() -> void:
	for iz in ZN:
		for ix in ZN:
			if zones[iz * ZN + ix] != GS.Zone.FOREST:
				continue
			var urban_park: bool = city.city_norm(-HALF + ix * ZRES, -HALF + iz * ZRES) < 1.05
			var k := 2 if rng.randf() < 0.35 else 1
			for j in k:
				var x := -HALF + (ix + rng.randf()) * ZRES
				var z := -HALF + (iz + rng.randf()) * ZRES
				if is_reserved(x, z, 2.0) or building_at(x, z) >= 0 or water_dist(x, z) < 2.0 or road_dist(x, z) < 1.0:
					continue
				var conifer := rng.randf() < (0.2 if urban_park else 0.75)
				var g := rng.randf_range(0.75, 1.1)
				var col := Color(0.09 * g, 0.24 * g, 0.08 * g) if conifer else Color(0.12 * g, 0.3 * g, 0.1 * g)
				add_tree(Vector2(x, z), rng.randf_range(1.0, 1.6) if conifer else rng.randf_range(0.9, 1.4), col, conifer)


## High-voltage lines leave every power plant for the edge of the map: lattice pylons with three
## sagging wires, skipped over houses, water and highways.
func _gen_power_lines() -> void:
	var steel := Color(0.5, 0.52, 0.55)
	var wire := Fx.solid(Color(0.25, 0.26, 0.28), 0.6, 0.5)
	for t in targets:
		if String(t.get("kind", "")) != "tpp":
			continue
		var c := Vector2(t.pos.x, t.pos.z)
		var a0 := rng.randf() * TAU
		for k in 2:
			var dir := Vector2.from_angle(a0 + k * (PI * 0.7 + rng.randf() * 0.6))
			var prev := Vector3.INF
			var d := 110.0
			while d < 1400.0:
				var p := c + dir * d
				d += 75.0
				if absf(p.x) > HALF - 20.0 or absf(p.y) > HALF - 20.0:
					break
				if water_dist(p.x, p.y) < 4.0 or road_dist(p.x, p.y) < 3.0 or building_at(p.x, p.y) >= 0 or is_reserved(p.x, p.y, 4.0):
					prev = Vector3.INF
					continue
				var h := 26.0
				for s in [-1.0, 1.0]:
					var q: Vector2 = p + Vector2(-dir.y, dir.x) * s * 2.2
					add_detail(Vector3(q.x, h * 0.5, q.y), Vector3(0.5, h, 0.5), 0.0, steel)
				var rot := atan2(dir.y, dir.x)
				add_detail(Vector3(p.x, h - 2.0, p.y), Vector3(0.4, 0.4, 11.0), -rot + PI * 0.5, steel)
				add_detail(Vector3(p.x, h - 6.0, p.y), Vector3(0.4, 0.4, 8.0), -rot + PI * 0.5, steel)
				add_footprint(p, Vector2(3, 3), 0.0, h, 1, "опора ЛЭП")
				var top := Vector3(p.x, h - 2.3, p.y)
				if prev != Vector3.INF:
					var side := Vector3(-dir.y, 0, dir.x)
					for w in [-4.5, 0.0, 4.5]:
						var a: Vector3 = prev + side * w
						var b: Vector3 = top + side * w
						var mid: Vector3 = (a + b) * 0.5 - Vector3(0, 2.2, 0)
						for seg in [[a, mid], [mid, b]]:
							var mi := MeshInstance3D.new()
							mi.mesh = Fx.cube(Vector3(0.12, 0.12, 1.0))
							mi.material_override = wire
							mi.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
							var sa: Vector3 = seg[0]
							var sb: Vector3 = seg[1]
							mi.transform = Transform3D(Basis.looking_at((sb - sa).normalized(), Vector3.UP) * Basis.from_scale(Vector3(1, 1, sa.distance_to(sb))), (sa + sb) * 0.5)
							add_child(mi)
				prev = top


## Parasols and changing cabins on the city beaches.
func _gen_beaches() -> void:
	var cols := [Color(0.9, 0.2, 0.2), Color(0.2, 0.5, 0.9), Color(0.95, 0.8, 0.2), Color(0.2, 0.7, 0.4), Color(0.95, 0.95, 0.9)]
	for iz in ZN:
		for ix in ZN:
			if zones[iz * ZN + ix] != GS.Zone.SAND or rng.randf() > 0.3:
				continue
			var x := -HALF + (ix + rng.randf()) * ZRES
			var z := -HALF + (iz + rng.randf()) * ZRES
			if water_dist(x, z) < 3.0 or building_at(x, z) >= 0 or city.city_norm(x, z) > 1.4:
				continue
			var c: Color = cols[rng.randi() % cols.size()]
			add_detail(Vector3(x, 1.1, z), Vector3(0.1, 2.2, 0.1), 0.0, Color(0.85, 0.85, 0.85))
			add_cyl(Vector3(x, 2.1, z), 1.3, 0.25, c)
			if rng.randf() < 0.4:
				add_detail(Vector3(x + 1.6, 0.15, z), Vector3(1.8, 0.3, 0.7), rng.randf() * PI, Color(0.9, 0.85, 0.7))


func _gen_labels() -> void:
	_labels = Node3D.new()
	add_child(_labels)
	for l in city.labels:
		_label(String(l[0]), l[1], l[3] if (l as Array).size() > 3 else Color(0.8, 1.0, 0.9, 0.85), int(l[2]))
	for d in city.districts:
		_label(String(d[0]), Vector3(d[1], 45, d[2]), Color(0.8, 1.0, 0.9, 0.85), 64)
	for t in targets:
		_label(String(t.name), t.pos + Vector3(0, 70, 0), Color(1.0, 0.55, 0.4, 0.9), 42, "◎ ")
	GS.language_changed.connect(refresh_labels)


func refresh_labels() -> void:
	for l in _labels.get_children():
		(l as Label3D).text = String(l.get_meta("prefix", "")) + GS.t(String(l.get_meta("key", "")))


func _label(text: String, pos: Vector3, color: Color, size: int, prefix := "") -> void:
	var l := Label3D.new()
	l.set_meta("key", text)
	l.set_meta("prefix", prefix)
	l.text = prefix + GS.t(text)
	l.font = GS.font
	l.font_size = size
	l.outline_size = 14
	l.modulate = color
	l.outline_modulate = Color(0, 0, 0, 0.7)
	l.billboard = BaseMaterial3D.BILLBOARD_ENABLED
	l.no_depth_test = true
	l.pixel_size = 0.5
	l.position = pos
	_labels.add_child(l)


# --- Environment ------------------------------------------------------------------------------
func _setup_env() -> void:
	env = Environment.new()
	env.background_mode = Environment.BG_SKY
	var sky := Sky.new()
	_sky_mat = Shaders.material(Shaders.SKY)
	sky.sky_material = _sky_mat
	env.sky = sky
	env.ambient_light_source = Environment.AMBIENT_SOURCE_COLOR
	env.reflected_light_source = Environment.REFLECTION_SOURCE_SKY
	env.tonemap_mode = Environment.TONE_MAPPER_ACES
	env.tonemap_exposure = 1.0
	env.tonemap_white = 6.0
	env.glow_enabled = true
	env.glow_intensity = 0.8
	env.glow_strength = 1.0
	env.glow_bloom = 0.05
	env.glow_hdr_threshold = 0.85
	env.glow_blend_mode = Environment.GLOW_BLEND_MODE_ADDITIVE
	env.adjustment_enabled = true
	env.fog_enabled = true
	# the sky draws its own horizon in the fog colour: the fog must not tint it again
	env.fog_sky_affect = 0.0
	_sky_mat.set_shader_parameter("sun_dir", _toward_light(SUN_DAY))
	_sky_mat.set_shader_parameter("moon_dir", _toward_light(SUN_NIGHT))
	_sky_mat.set_shader_parameter("cloud_cover", 0.3 + 0.3 * float(city.seed % 7) / 6.0)
	var we := WorldEnvironment.new()
	we.environment = env
	add_child(we)
	_sun = DirectionalLight3D.new()
	_sun.directional_shadow_max_distance = 900.0
	add_child(_sun)


## Where the directional light comes from (the sun by day, the moon by night): its rotation in
## degrees, and the unit vector pointing back at it for the sky.
const SUN_DAY := Vector3(-52, -35, 0)
const SUN_NIGHT := Vector3(-38, 155, 0)
## Haze on the horizon: day blue-grey, night the orange-brown of the city lights. Fog and sky
## share it, so the far land fades into the sky without a seam.
const HAZE_DAY := Color(0.7, 0.77, 0.85)
const HAZE_NIGHT := Color(0.095, 0.075, 0.082)


static func _toward_light(rot_deg: Vector3) -> Vector3:
	return Basis.from_euler(rot_deg * (PI / 180.0)) * Vector3(0, 0, 1)


## 0 low, 1 high, 2 ultra: shadows, glow and street life from high; the shaders read the same
## level (global "gfx") for clouds, stars, window interiors and water reflections.
func apply_quality(q: int) -> void:
	RenderingServer.global_shader_parameter_set("gfx", float(q))
	_sun.shadow_enabled = q >= 1
	env.glow_enabled = q >= 1
	get_viewport().msaa_3d = Viewport.MSAA_2X if q >= 1 else Viewport.MSAA_DISABLED
	if b_traffic:
		b_traffic.set_visible(q >= 1)
		b_cars.set_visible(q >= 1)
		b_people.set_visible(q >= 1)
		b_detail.set_visible(q >= 1)
		b_parked.set_visible(q >= 1)


func set_night(n: float) -> void:
	night = clampf(n, 0.0, 1.0)
	RenderingServer.global_shader_parameter_set("night", night)
	_sun.rotation_degrees = SUN_DAY.lerp(SUN_NIGHT, night)
	_sun.light_color = Color(1.0, 0.93, 0.8).lerp(Color(0.55, 0.65, 1.0), night)
	_sun.light_energy = lerpf(1.45, 0.3, night)
	env.ambient_light_color = Color(0.56, 0.62, 0.74).lerp(Color(0.15, 0.15, 0.25), night)
	env.ambient_light_energy = lerpf(0.6, 0.8, night)
	env.tonemap_exposure = lerpf(1.0, 1.3, night)
	var haze := HAZE_DAY.lerp(HAZE_NIGHT, night)
	env.fog_light_color = haze
	env.fog_density = lerpf(0.00017, 0.00042, night) * fog_scale
	env.adjustment_saturation = lerpf(1.12, 1.04, night)
	env.adjustment_contrast = lerpf(1.06, 1.1, night)
	env.glow_intensity = lerpf(0.45, 0.95, night)
	env.glow_bloom = lerpf(0.02, 0.07, night)
	if _sky_mat:
		_sky_mat.set_shader_parameter("haze_day", Vector3(HAZE_DAY.r, HAZE_DAY.g, HAZE_DAY.b))
		_sky_mat.set_shader_parameter("haze_night", Vector3(HAZE_NIGHT.r, HAZE_NIGHT.g, HAZE_NIGHT.b))


## 0 disables haze (overhead map view), 1 = normal atmosphere.
func set_fog_scale(s: float) -> void:
	fog_scale = s
	env.fog_enabled = s > 0.0
	set_night(night)


# --- Debug: top-down plan of the generated city (headless-friendly) ------------------------------------
## Writes a 1000×1000 PNG of the square (cx, cz, size): zones, water, highways, rails, buildings,
## bridges, reserves. The whole map by default (2 m per pixel).
func dump_plan(path: String, cx := 0.0, cz := 0.0, size := 2000.0) -> void:
	var n := 1000
	var k := size / n
	var ox := cx - size * 0.5
	var oz := cz - size * 0.5
	var img := Image.create_empty(n, n, false, Image.FORMAT_RGB8)
	for py in n:
		for px in n:
			var x := ox + (px + 0.5) * k
			var z := oz + (py + 0.5) * k
			var c: Color
			if water_dist(x, z) < 0.0:
				c = Color(0.15, 0.35, 0.7)
			else:
				match zone_at(x, z):
					GS.Zone.FOREST:
						c = Color(0.15, 0.4, 0.15)
					GS.Zone.CITY:
						c = Color(0.55, 0.55, 0.55)
					GS.Zone.SAND:
						c = Color(0.85, 0.78, 0.5)
					_:
						c = Color(0.62, 0.66, 0.42) if urban_at(x, z) == 0 else Color(0.7, 0.7, 0.5)
				if road_dist(x, z) < 0.0:
					c = Color(0.15, 0.15, 0.15)
			img.set_pixel(px, py, c)
	for i in fp_center.size():
		var cc := fp_center[i]
		var hs := fp_half[i]
		var col := Color(0.95, 0.35, 0.25) if fp_name.has(i) else Color(0.25, 0.22, 0.3).lerp(Color(1, 1, 0.9), clampf(cc.y / 90.0, 0.0, 1.0))
		if is_bridge(i):
			col = Color(1.0, 0.85, 0.1)
		var ca := cos(fp_rot[i])
		var sa := sin(fp_rot[i])
		var r := hs.length()
		for py in range(maxi(0, int((cc.z - r - oz) / k)), mini(n - 1, int((cc.z + r - oz) / k)) + 1):
			for px in range(maxi(0, int((cc.x - r - ox) / k)), mini(n - 1, int((cc.x + r - ox) / k)) + 1):
				var dx := ox + (px + 0.5) * k - cc.x
				var dz := oz + (py + 0.5) * k - cc.z
				var lx := dx * ca + dz * sa
				var lz := -dx * sa + dz * ca
				if absf(lx) <= hs.x and absf(lz) <= hs.y:
					img.set_pixel(px, py, col)
	for rv in _reserved:
		for q in 48:
			var a := TAU * q / 48.0
			var px := int((rv.x + cos(a) * rv.z - ox) / k)
			var py := int((rv.y + sin(a) * rv.z - oz) / k)
			if px >= 0 and py >= 0 and px < n and py < n:
				img.set_pixel(px, py, Color(1, 0, 1))
	for d in city.districts:
		var px := int((float(d[1]) - ox) / k)
		var py := int((float(d[2]) - oz) / k)
		for t in range(-4, 5):
			for q in [Vector2i(px + t, py), Vector2i(px, py + t)]:
				if q.x >= 0 and q.y >= 0 and q.x < n and q.y < n:
					img.set_pixel(q.x, q.y, Color(1, 1, 0))
	img.save_png(path)
	print("UAD: plan of %s saved to %s" % [city.id, path])
